eureka:
  client:
    register-with-eureka: true   # Enable registration
    fetch-registry: true         # Enable fetching registry
    service-url:
      defaultZone: http://localhost:8761/eureka  # Eureka Server URL

  instance:
    prefer-ip-address: true
